<?php

/**
 * @var \Smartosc\Article\Block\Display $block
 */

$data = $block->article();

?>

<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
        margin-top: 30px;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }

    .post-id {
        width: 2%
    }

    .post-name {
        width: 30%
    }

</style>

<table>
    <tr>
        <th class="post-id">Id</th>
        <th class="post-name">Name</th>
        <th>URL</th>
        <th>Content</th>
    </tr>
    <?php
    foreach ($data as $article) {
        echo
            '<tr>
                <td>' . $article['id'] . '</td>
                <td>' . $article['name'] . '</td>
                <td>' . $article['url_key'] . '</td>
                <td>' . $article['post_content'] . '</td>
             </tr>';
    }
    ?>
</table>

</body>
</html>