<?php

/**
 * @var \Smartosc\Article\Controller\Index\Insert $controller
 */

var_dump($controller);
die;

?>

<form class="" action="" id="vky-test-form" method="post">
    <fieldset class="fieldset">
        <legend class="legend"><span>Insert an article</span></legend><br>

        <div class="field title">
            <label class="label" for="title"><span>Name</span></label>
            <div class="control">
                <input name="name" id="name" title="Name" value="" class="input-text" type="text">
            </div>
        </div>

        <div class="field content">
            <label class="label" for="content"><span>Content</span></label>
            <div class="control">
                <textarea name="content" id="content" title="Content" class="input-text" cols="5" rows="3"></textarea>
            </div>
        </div>

    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="Submit" class="action submit primary">
                <span>Submit</span>
            </button>
        </div>
    </div>
</form>

</body>
</html>